# Generated by Django 5.0.1 on 2024-01-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='tags',
        ),
    ]
