# Generated by Django 5.0.1 on 2024-01-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_technology_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
    ]
