# Generated by Django 5.0.1 on 2024-01-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('exp1', models.TextField()),
                ('exp2', models.TextField()),
                ('exp3', models.TextField()),
                ('c_web', models.CharField(max_length=30)),
                ('c_red1', models.CharField(max_length=30)),
                ('c_red2', models.CharField(max_length=30)),
                ('c_email', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, upload_to='users_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_user',
        ),
        migrations.AddField(
            model_name='project',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.persona'),
        ),
    ]
