# Generated by Django 5.0.1 on 2024-01-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_persona_remove_project_id_user_project_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='c_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='exp1',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='exp2',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='exp3',
        ),
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(default='1234', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.persona')),
            ],
        ),
    ]
