# Generated by Django 5.0.1 on 2024-02-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_experiences_experience_remove_persona_c_red1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.TextField(help_text='Describe tu cargo y funciones.'),
        ),
    ]
