# Generated by Django 5.0.1 on 2024-02-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_experience_title_alter_experience_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='init_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
