# Generated by Django 5.0.1 on 2024-02-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('web', models.URLField(blank=True)),
                ('rrss_1', models.URLField(blank=True)),
                ('rrss_2', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='1234', max_length=30)),
                ('image', models.FileField(blank=True, upload_to='users_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('init_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('experience', models.TextField(help_text='Describe tu cargo y funciones.')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.persona')),
            ],
        ),
    ]
